AWSTemplateFormatVersion: '2010-09-09'
Description: Simple Hello World CloudFormation stack
Resources:
  HelloWorldBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'hello-world-bucket-${AWS::Region}-${AWS::AccountId}'
